### ISSUE TITLE
Bot not sending any responses

### ISSUE THREAD

**Issue by feroleek** [fhodun/testshoter#18]
I installed bot on my vps (Ubuntu 16.04). I started bot, it appears online, I try to interact with it by typing `>version`. There is no response from bot on discord chat, but in putty I see an error:
```
 npm start

> testshoter@2.2.1 start /root/testshoter
> ts-node -r dotenv/config -r tsconfig-paths/register .

Logged in!
(node:473) UnhandledPromiseRejectionWarning: TypeError: fields.flat is not a function
    at Function.normalizeFields (/root/testshoter/node_modules/discord.js/src/structures/MessageEmbed.js:450:8)
    at MessageEmbed.setup (/root/testshoter/node_modules/discord.js/src/structures/MessageEmbed.js:78:91)
    at new MessageEmbed (/root/testshoter/node_modules/discord.js/src/structures/MessageEmbed.js:18:10)
    at embedLikes.map.e (/root/testshoter/node_modules/discord.js/src/structures/APIMessage.js:166:40)
    at Array.map (<anonymous>)
    at APIMessage.resolveData (/root/testshoter/node_modules/discord.js/src/structures/APIMessage.js:166:31)
    at TextChannel.send (/root/testshoter/node_modules/discord.js/src/structures/interfaces/TextBasedChannel.js:166:62)
    at /root/testshoter/src/discord/misc.ts:12:25
    at Generator.next (<anonymous>)
    at /root/testshoter/src/discord/misc.ts:8:71
(node:473) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:473) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
I did something wrong or what? Need fast help. 
pzdr

**Comment by gbaranski** [comment]
> I installed bot on my vps (Ubuntu 16.04). I started bot, it appears online, I try to interact with it by typing `>version`. There is no response from bot on discord chat, but in putty I see an error:
> 
> ```
>  npm start
> 
> > testshoter@2.2.1 start /root/testshoter
> > ts-node -r dotenv/config -r tsconfig-paths/register .
> 
> Logged in!
> (node:473) UnhandledPromiseRejectionWarning: TypeError: fields.flat is not a function
>     at Function.normalizeFields (/root/testshoter/node_modules/discord.js/src/structures/MessageEmbed.js:450:8)
>     at MessageEmbed.setup (/root/testshoter/node_modules/discord.js/src/structures/MessageEmbed.js:78:91)
>     at new MessageEmbed (/root/testshoter/node_modules/discord.js/src/structures/MessageEmbed.js:18:10)
>     at embedLikes.map.e (/root/testshoter/node_modules/discord.js/src/structures/APIMessage.js:166:40)
>     at Array.map (<anonymous>)
>     at APIMessage.resolveData (/root/testshoter/node_modules/discord.js/src/structures/APIMessage.js:166:31)
>     at TextChannel.send (/root/testshoter/node_modules/discord.js/src/structures/interfaces/TextBasedChannel.js:166:62)
>     at /root/testshoter/src/discord/misc.ts:12:25
>     at Generator.next (<anonymous>)
>     at /root/testshoter/src/discord/misc.ts:8:71
> (node:473) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
> (node:473) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
> ```
> 
> I did something wrong or what? Need fast help.
> pzdr

Update Node.JS to latest LTS, if its not possible change target in tsconfig.json to ES5
